Сделал ДЗ
Karenanna/RecipeApp1 pull request #1
Opened 2023-01-15 15:14 UTC by Karenanna

Проверьте пожалуйста ДЗ, спасибо

2023-01-15 18:46 UTC, OlgaLugacheva requested changes

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/IngredientsController.java
> +                                 @RequestParam("measure") String measure) {
только не через параметры а через RequestBody и Ingredient

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/RecipeController.java
> +                            @RequestParam("instruction") List<String> instruction) {
RequestBody Recipe

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/RecipeService.java
> +    String addRecipe (String name, String cookingTime, List<String> ingredients, List<String> instruction);
Пусть принимает в параметрах Recipe

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +    String IngredientsService  (String name, String cookingTime, List<String> ingredients, List<String> instruction);
что это за метод? что он делает и почему такое странное название ?

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +    @Override
нам нужно здесь хранилище, например, карта для хранения рецептов 

 private final Map<Integer, Recipe> recipeMap = new HashMap<>();

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +        return null;}
в этих методах нужно работать с мапой - добавлять и получать рецепты
например
  recipeMap.put(this.counter++, recipe);

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        return null;
здесь как и в дурготм сервисе нужно работать с мапой ингридиентов

2023-01-15 18:46 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/model/Recipe.java
> +    private List<String>  ingredients;
`List<Ingredients>`

2023-01-16 19:45 UTC, Karenanna commented
Проверьте пожалуйста ДЗ, сделал работу над ошибками, спасибо за статьи. Метод recipeMap.put(this.counter++, recipe) не могу добавить в проект, программа ругается.

2023-01-17 06:41 UTC, OlgaLugacheva requested changes

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/IngredientsController.java
> +        if (ingredientsService.getIngredientsService() != null) {
эта проверка лишняя

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/IngredientsController.java
> +    public String getIngredients(@PathVariable() int id) {
`@PathVariable` без скобочек

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/RecipeController.java
> +    public String getRecipe(@PathVariable("id") int id) {
@PathVariable без скобочек

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/RecipeController.java
> +    @GetMapping("/id")
` @GetMapping("/{id}")`

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +    String getIngredientsService();
getIngridient

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        return null;
например так 

```
public String getIngredient(Integer id) {
        return ingredientsMap.get(id);
}
```

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +    private final Map<Integer, String> ingredientsMap = new HashMap<>();
карта должна хранить не строки а ингредиенты

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +     String recipe;
лишнее поле

2023-01-17 06:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +        return null;
см аналогичный комментарий в другом классе

2023-01-17 09:27 UTC, Karenanna commented
Спасибо за замечание, сделал работу над ошибками

2023-01-17 16:41 UTC, OlgaLugacheva requested changes

2023-01-17 16:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +    String getIngredientsService();
код здесь должен выглядеть так 

```
Ingredients getIngredient(Integer id);

Ingredients addIngredient(Ingredients ingredient);

```

2023-01-17 16:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        return null;
здесь тогда код должен выглядеть так 

 ```
   private static Integer counter = 0; 
    private final Map<Integer, Ingredients> ingredientsMap = new HashMap<>();

    @Override
    public Ingredients getIngredient(int id) {
        return ingredientsMap.get(id);
    }

    @Override
    public Ingredients addIngredient(Ingredients ingredient) {
        return ingredientsMap.put(counter++, ingredient);
    }
```

2023-01-17 16:41 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        return null;
в другом сервисе - - исправить аналогично

2023-01-17 21:02 UTC, Karenanna commented
Сделал как Вы сказали, но где Вы написали @Override там программа красным высвечивает и предлагает свои версии с @Override, фотки прикрепил в ЛК чтобы Вы увидели

2023-01-18 18:40 UTC, Karenanna commented
Проверьте пожалуйста ДЗ

2023-01-18 19:48 UTC, OlgaLugacheva requested changes

2023-01-18 19:48 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/RecipeController.java
> +    @GetMapping("{/id}")
@GetMapping("/{id}")

2023-01-18 19:48 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/model/Ingredients.java
> +@AllArgsConstructor
`нужен еще @NoArgsConstructor тогда`

2023-01-18 19:48 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/model/Recipe.java
> +@AllArgsConstructor
нужен еще @NoArgsConstructor тогда

2023-01-18 19:48 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +        return null;
не надо null возвращать, просто 

`Ingredients addIngredient(Ingredients ingredient);`

2023-01-18 19:48 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +    }
убрать

2023-01-18 20:23 UTC, Karenanna commented
Проверьте пожалуйста ДЗ

2023-01-19 08:09 UTC, Karenanna commented
Сделал как в примере

2023-01-19 18:08 UTC, OlgaLugacheva requested changes

2023-01-19 18:08 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/controllers/IngredientsController.java
> +       return  IngredientsService.addIngredient(ingredients);
`  return  ingredientsService.addIngredient(ingredients);`

2023-01-19 18:08 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +    }
`    Ingredients addIngredient(Ingredients ingredient);`

2023-01-19 19:23 UTC, Karenanna commented
Проверьте пожалуйста ДЗ

2023-01-20 06:23 UTC, OlgaLugacheva approved these changes

2023-01-21 22:07 UTC, Karenanna commented
Проверьте пожалуйста ДЗ Postman

2023-01-23 13:16 UTC, Karenanna commented
Проверьте пожалуйста ДЗ, спасибо

2023-01-23 20:29 UTC, Karenanna commented
Проверьте пожалуйста ДЗ Библиотеки, спасибо

2023-01-25 20:33 UTC, Karenanna commented
Проверьте пожалуйста ДЗ Потоки

2023-01-26 18:20 UTC, alekseykoshelev requested changes

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/impl/FilesServiceImpl.java
> +           return Files.readString(Path.of(dataFilePath,  dataFileNameRecipe, dataFileNameIngredients));
Тут нужно читать из одного файла. Ты передаешь сразу оба. Лучше сделать аргумент у функции, `filename` и передавать туда разные значения.

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/impl/FilesServiceImpl.java
> +    private String dataFileNameRecipe;
Это поле должно быть в сервисе рецептов. Аналогично и про ингредиенты.

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/impl/FilesServiceImpl.java
> +          Path path = Path.of(dataFilePath,  dataFileNameRecipe, dataFileNameIngredients);
Такая же проблема как и с `readFromFile`

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/RecipeService.java
> +    void saveToFile();
Эти методы можно не добавлять в интерфейс. Их можно сделать приватными внутри имплементации. Они не нужны нигде снаружи.

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/RecipeService.java
> +
Не совсем к этой домашке коммент, но все же. У тебя тут два метода удаления рецепта
`boolean deleteRecipe(int id);`
`Recipe removeRecipe(int id);`
Первый выглядит лишним, тем более, что в реализации ты ничего не делаешь, а просто возвращаешь false.

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsService.java
> +    void saveToFile();
Аналогичный момент, как и с рецептами.

2023-01-26 18:20 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +            saveToFile();
На удалении сохраняешь, а на добавлении ингредиента нет.

2023-01-29 11:08 UTC, Karenanna commented
Поправил код, эти ошибки ушли, но в консоли пишет что ошибка в FilesServic

2023-02-01 08:06 UTC, Karenanna commented
Проверьте ДЗ

2023-02-03 20:36 UTC, Karenanna commented
Проверьте пожалуйста ДЗ

2023-02-08 20:51 UTC, Karenanna commented
Проверьте пожалуйста ДЗ HTTP файлы

2023-02-12 10:53 UTC, Karenanna commented
Проверьте пожалуйста ДЗ HTTP файлы, сделал работу над ошибками

2023-02-12 12:17 UTC, isavinov requested changes

2023-02-12 12:17 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/controllers/FilesController.java
> +        return uploadDataFile("/importrecipe", file);
Здесь ты передаешь "/importrecipe", а в методе uploadDataFile ожидаешь `value.equals("importrecipe")`.  Соотвественно при upload рецептов ты  получшь ошибку

2023-02-13 19:14 UTC, Karenanna commented
Поменял код

2023-02-14 12:38 UTC, isavinov requested changes

2023-02-14 12:38 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/controllers/FilesController.java
> +    @PostMapping(value = "importingredients", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
`@PostMapping(value = "/importingredients", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)`

2023-02-14 12:38 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/FilesServiceImpl.java
> +public class FilesServiceImpl implements FilesService {
Нет реализации метода `cleanDataFile()`, тебе нужно либо реализовать этот метод в сервисе (так как он реализует интерфейс), либо удалить `cleanDataFile()` из интерфейса

2023-02-14 12:38 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +public class IngredientsServiceImpl implements IngredientsService {
Нет реализации метода `importFile(MultipartFile)`

2023-02-14 12:38 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +public class RecipeServiceImpl implements RecipeService {
Нет реализации метода `importFile(MultipartFile)`

2023-02-14 20:18 UTC, Karenanna commented
Проверьте пожалуйста ДЗ, сделал работу над ошибками

2023-02-15 21:04 UTC, Karenanna commented
HTTP

2023-02-16 09:31 UTC, isavinov requested changes

2023-02-16 09:31 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/controllers/FilesController.java
> +        recipeService.importFile(file);
Здесь ты вызываешь метод `importFile(file);` у класса объекты `RecipeServiceImpl`. В классе `RecipeServiceImpl` этого метода нет, соотвественно вызывать нечего. В класса  `RecipeServiceImpl` нужно сделать метод `importFile(file);`, который будет сохранять файл на диск

2023-02-16 09:31 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/controllers/FilesController.java
> +        ingredientsService.importFile(file);
Аналогичный комментарий. Здесь ты вызываешь метод `importFile(file);` у класса объекты `IngredientsServiceImpl`. В классе `IngredientsServiceImpl` этого метода нет, соотвественно вызывать нечего. В класса  `IngredientsServiceImpl` нужно сделать метод importFile(file);, который будет сохранять файл на диск

2023-02-16 09:31 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/controllers/FilesController.java
> +    public ResponseEntity<Void> uploadDataFile(@RequestParam MultipartFile file) {
Этот метод можно смело удалить, так как у тебя есть `uploadRecipeDataFile` и `uploadIngredientsDataFile`

2023-02-16 10:36 UTC, Karenanna commented
Добавил метод importFile

2023-02-16 20:31 UTC, Karenanna commented
Добавил логиу

2023-02-17 10:43 UTC, isavinov requested changes

2023-02-17 10:43 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +    public void importFile(MultipartFile file) {
Это же даже не компилируется, нельзя внутри метода объявить еще один метод. К тому же с аннотациями из Controller

2023-02-17 10:43 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +    public void importFile(MultipartFile file) {
Тот же комментарий

2023-02-17 10:43 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        @PostMapping(value = "/import/{dataNameFile}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
Должно выглядеть как-то так
```
@Override
    public void importFile(MultipartFile file) {
        File dataFile = new File(dataFilePath + "/" + dataFileName);
        try (FileOutputStream fos = new FileOutputStream(dataFile)) {
            IOUtils.copy(file.getInputStream(), fos);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

2023-02-18 06:47 UTC, Karenanna commented
После исправления ошибок нет

2023-02-18 12:49 UTC, isavinov requested changes

2023-02-18 12:49 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +    private File dataFilePath;
@Value("${path.to.data.file}")
private String dataFilePath;

2023-02-18 12:49 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +    private File dataFilePath;
```
@Value("${path.to.data.file}")
private String dataFilePath;
```

2023-02-18 12:49 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +        File dataFile = new File(dataFilePath + "/" + dataFileName);
Значение dataFilePath у тебя нигде не выставляется, оно всегда null в твоем случае. Оставил коммент выше как правильно проинициализировать значением из проперти файла

2023-02-18 12:49 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/RecipeServiceImpl.java
> +        File dataFile = new File(dataFilePath + "/" + dataFileName);
Значение dataFilePath у тебя нигде не выставляется, оно всегда null в твоем случае. Оставил коммент выше как правильно проинициализировать значением из проперти файла

2023-02-18 22:44 UTC, Karenanna commented
Http

2023-02-19 13:34 UTC, isavinov requested changes

2023-02-19 13:34 UTC, isavinov commented on src/main/java/pro/sky/recipeapp1/services/impl/IngredientsServiceImpl.java
> +    private File dataFilePath;
Удали `private File dataFilePath;`
Оставь только
```
@Value("${path.to.data.file}") 
private String dataFilePath;
```

Обрати внимание на имя **`dataFilePath`**, обязательно такое

2023-02-19 14:28 UTC, Karenanna commented
Убрал private File dataFilePath

2023-02-19 18:58 UTC, Karenanna commented
path

2023-02-20 10:29 UTC, isavinov approved these changes

2023-02-21 07:20 UTC, merged